image: paymentsos/mesos-frameworks:build

stages:
  - test

variables:
  IMAGE: $CI_REGISTRY_IMAGE
  BASE_IMAGE: $CI_REGISTRY_IMAGE/base
  TAG: $CI_COMMIT_TAG
  REF_NAME: $CI_COMMIT_REF_NAME
  COMMIT_SHA: $CI_COMMIT_SHA


Tests:
  stage: test
  script:
    - NPM_ENV=dev npm install
    - npm install -g istanbul
    - istanbul cover ./node_modules/mocha/bin/_mocha tests/*.test.js tests/*.integration.js

Build:
  stage: build
  script:
    - ./build.sh